### ISSUE TITLE
Small naive optimization

### ISSUE THREAD

**Issue by maximelkin** [cd48b153/hashmap-contest#3]
Object.create(null) instead of {} has a little more performance for first 2 cases.

**Comment by cd48b153** [comment]
|              |       1M-50K |      2M-100K |        3M-5K |
| ------------ | ------------ | ------------ | ------------ |
|   es6-concat |         0.82 |         0.92 |         0.55 |
|    es6-stack |         0.52 |         0.41 |         0.36 |
|      float64 |         0.35 |         0.35 |         0.24 |
|      hashmap |         2.94 |         2.86 |         1.52 |
|         list |         0.34 |         0.30 |         0.22 |
|  naive-stack |         1.65 |         1.79 |         1.16 |
|        naive |         1.00 |         1.00 |         1.00 |
|         trie |         0.76 |         0.92 |         0.57 |

**Comment by cd48b153** [comment]
`list` and `float64` are now almost the same
